#!/bin/bash

bash -c "PATH=$PATH:$HOME/.local/bin LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 jupyter notebook --no-browser --notebook-dir=$HOME --NotebookApp.allow_remote_access=True --NotebookApp.allow_origin=\*"
