#!/bin/bash

# Enable ssh-agent
if [ -z "$SSH_AUTH_SOCK" ]; then
	eval "$(ssh-agent)"
fi

# Add ssh key (uncomment if needed)
# ssh-add ~/.ssh/id_rsa

ssh -tt -R 80:localhost:8888 nokey@localhost.run > ./ssh.log
